### ISSUE TITLE
Add reference link to mention of "N+1 Query Problem"

### ISSUE THREAD

**Issue by chaotic3quilibrium** [AugustNagro/magnum#15]
In README.md, please add the following reference link to the mentioning of the "N+1 Query Problem". It's for those of us who haven't seen this particular problem described using this vernacular before:
https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping

**Comment by AugustNagro** [comment]
Done. Thanks for the link.
