### ISSUE TITLE
findAll returns zero results from H2

### ISSUE THREAD

**Issue by objektwerks** [AugustNagro/magnum#17]
Magnum findAll returns zero results from H2 - when it should return a result of 1.

The following project - https://github.com/objektwerks/magnum - can be used via - sbt clean test - to reproduce this issue. Read the test console output for details. The project code will provide additional details.

**Comment by AugustNagro** [comment]
We have good coverage of H2 including `findAll`: https://github.com/AugustNagro/magnum/blob/master/magnum/src/test/scala/H2Tests.scala

I think the problem in your JMH test is that you need a

```
@Setup
def setup(): Unit = ???
``` 

Method that populates the database rows. The rows inserted from 

```
  @Benchmark
  def addTodo(): Todo =
```

Will not be visible from the other benchmarks; the in-memory H2 instance is fresh.

Please share the results when done, I'd like to see them. I expect Magnum to perform well, given its low abstraction & code size.

**Comment by objektwerks** [comment]
In addition to the Github documentation, I referenced H2Tests extensively to build my project. So I was quite surprised to see findAll fail in my simple StoreTest. :)

Did you run - sbt clean test and read the test console output?

The issue is with findAll failing to return a Vector of length == 1.
...

At this time, my issue is not with sbt:jmh and Performance.

I have a Quill project ( https://github.com/objektwerks/quill ) that mimics my Magnum project; and for both projects - running sbt:jmh fails with this issue: https://github.com/sbt/sbt-jmh/issues/192

As I recall, sbt:jmh used to work with Java 8. :) It works just fine in my non-jdbc projects.

The Quill project StoreTest, though, passes; where the Magnum StoreTest fails.

**Comment by AugustNagro** [comment]
The problem in StoreTest is that the runscript is dropping table Todo every time a new connection is made.

You can change `url` to `url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"`, and then initialize the db once:

```
  Using.Manager(use =>
    val con = use(ds.getConnection)
    val stmt = use(con.createStatement)
    val sql = Files.readString(Path.of("ddl.sql"))
    println("executing \n" + sql)
    stmt.execute(sql)
  ).get
```

Quill maintains the single connection, whereas Magnum creates a new connection every `connect`/`transact` call. 

Note that you should be calling `transact` at a higher scope and then share the connection.

So for example, call `transact` in StoreTest, make each Store method require the implicit:

```
  def count(): Long =
    transact(ds, withRepeatableRead):
      repo.count
```

Becomes

```
  def count(using DbTx): Long = repo.count
```

This will then match Quill's behavior. You should also replace `transact` with `connect`, because I don't think Quill is running with transactions.

**Comment by objektwerks** [comment]
**Brilliant!** I refactored accordingly, and everything works as expected. **Thanks!** And apologies for failing to understand the finer points of Magnum. :)

Currently, I use transact for writes and connect for reads.

**Comment by objektwerks** [comment]
Closed.

**Comment by AugustNagro** [comment]
Glad it's working now.

> Currently, I use transact for writes and connect for reads.

Why? If you have this running in parallel:

```
myWrite()
myRead
myWrite2()
```

You will easily have dirty reads: https://www.postgresql.org/docs/current/transaction-iso.html

To use transactions safely you would use DbTx and DbCon: https://github.com/AugustNagro/magnum#type-safe-transaction--connection-management

> After my initial euphoria wore off a bit, I noticed having Magnum code in Performance and StoreTest ( user code ) was not ideal. So I added Delegate ( a level of indirection ) to Store, allowing me to remove all Magnum code from my user code.

There's no reason to use transactions for methods that only execute one sql statement. The whole point of [transactions](https://en.wikipedia.org/wiki/Database_transaction) is that they roll-back if your code throws an exception. But that won't be possible using your Store class.

> Question: What is ScalikeJdbc ** doing that Magnum and Quill aren't doing?

Did you try the fix suggested in https://github.com/AugustNagro/magnum/issues/17#issuecomment-1711139093 ?

**Comment by objektwerks** [comment]
In Store and Delegate, I use ```transact/DbTx and connect/DbCon```, for add/update and list, respectively.

Note, ScalikeJdbc has ```DB localTx and DB readOnly```, while Quill has ```transaction and query```. Other Jdbc libraries function similarly.

On an insert or update, I want a transaction/rollback capability for 1 or more sql statements. On a database select, I don't want a transaction - just a read only capability. I assumed I had those capabilities with ```transact/DbTx``` and ```connect/DbCon```, respectively.

With all other Scala Jdbc libraries, I can readily converge Store and Delegate. Magnum, as you explain above, requires me to separate ```transact/connect``` from ```DbTx/DbCon`` in an effort to keep Magnum code out of my user code.

I don't know how else to explain it. :) Naturally, remote communications has it challenges. ;) Thanks for your help!
...

I did try to your ```setup``` suggestion with Performance, but to no avail. I suspect a class loader issue; but who knows. ;)

**Comment by objektwerks** [comment]
Using jmh 0.4.7 and JDK 22, my benchmark run works!

```
OpenJDK Runtime Environment Zulu22.28+91-CA (build 22+36), **Scala 3.4.1-RC2**, Apple M1
1. addTodo - 4.455
2. listTodos - 1.901
3. updateTodo - 3.648
Total time: 604 s (10:04), 10 warmups, 10 iterations, average time in microseconds, completed **2024.3.21**
```
