### ISSUE TITLE
Support for JSONB

### ISSUE THREAD

**Issue by williamhaw** [AugustNagro/magnum#18]
hi @AugustNagro, thanks for this amazing library!

Is it possible to decode JSONB columns from Postgres directly? Or should I query it as string and then decode it separately?

**Comment by AugustNagro** [comment]
Thanks William, IIRC the postgres JDBC driver doesn't have a JsonB type, so you'll have to use String and decode separately.

If you find it's a common pattern in your code, one option would be to

1. Define a 'marker type' 
3. Add the marker on your Json case class fields as a intersection type
4. Create a DbCodec that knows how to deserialize

For example:

```scala
opaque type Json = Any

// in a different file
case class Friend(id: Int, name: String) derives MyJsonCodec

case class User(id: Int, friends: Seq[Friend] & Json) derives DbCodec

given JsonBCodec[A](using jsonCodec: MyJsonCodec[A]): DbCodec[A & Json] = ???
```

**Comment by williamhaw** [comment]
Thanks!

**Comment by AugustNagro** [comment]
My pleasure. Feel free to re-open or file another issue if anything comes up.
