### ISSUE TITLE
Support Json & XML Column Deserialization

### ISSUE THREAD

**Issue by AugustNagro** [AugustNagro/magnum#27]

**Comment by guizmaii** [comment]
What is missing for JSON support?

**Comment by AugustNagro** [comment]
Hey, sorry I missed your response @guizmaii.

> What is missing for JSON support?

I hope we can discover that as part of this issue. I haven't had the chance to use this library yet with jsonb / xml columns.

Ideally, we'd add some new test cases with Json / XML columns, and see what the limitations are.

Maybe we'll end up with the ability to write a table like

```sql
create table my_table (
  id bigint primary key,
  content jsonb not null
);
```

And entity class something like

```scala
import com.augustnagro.magnum.pg.json.circe.CirceDbCodec

case class MyContent(a: A, b: B) derives CirceDbCodec
object MyContent:
  given circeCodec = ...

@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
case class MyTable(
  @Id id: Long,
  content: MyContent
) derives DbCodec
```

The idea being that when you call `myTableRepo.findById(x)`, it deserializes `content` into a PgObject, get's the value, deserializes it with the user's Circe codec, and puts it into the MyTable result.

**Comment by jivanic-demystdata** [comment]
@AugustNagro What do you think of these implementation to support `JSON` and `JSONB`, it's inspired by how Quill is doing it.

(I'm using zio-json `JsonCodec`)

```scala
/**
 * Adds support to JSON columns type to Magnum
 */
final case class Json[A](content: A)
object Json {
  given [A: JsonCodec]: DbCodec[Json[A]] =
    new DbCodec[Json[A]] {
      override val queryRepr: String = "?::json"
      override val cols: IArray[Int] = IArray(Types.JAVA_OBJECT)

      override def readSingle(resultSet: ResultSet, pos: Int): Json[A] = {
        val r = resultSet.getString(pos)
        Json(JsonCodec[A].decoder.decodeJson(r).getOrElse(throw ShouldNeverHappenException(s"Failed to decode JSON from $r")))
      }

      def writeSingle(entity: Json[A], ps: PreparedStatement, pos: Int): Unit = {
        val jsonObject = PGobject()
        jsonObject.setType("json")
        jsonObject.setValue(JsonCodec[A].encoder.encodeJson(entity.content).toString)
        ps.setObject(pos, jsonObject)
      }
    }
}

/**
 * Adds support to JSONB columns type to Magnum
 */
final case class JsonB[A](content: A)
object JsonB {
  given [A: JsonCodec]: DbCodec[JsonB[A]] =
    new DbCodec[JsonB[A]] {
      override val queryRepr: String = "?::jsonb"
      override val cols: IArray[Int] = IArray(Types.JAVA_OBJECT)

      override def readSingle(resultSet: ResultSet, pos: Int): JsonB[A] = {
        val r = resultSet.getString(pos)
        JsonB(JsonCodec[A].decoder.decodeJson(r).getOrElse(throw ShouldNeverHappenException(s"Failed to decode JSON from $r")))
      }

      def writeSingle(entity: JsonB[A], ps: PreparedStatement, pos: Int): Unit = {
        val jsonObject = PGobject()
        jsonObject.setType("jsonb")
        jsonObject.setValue(JsonCodec[A].encoder.encodeJson(entity.content).toString)
        ps.setObject(pos, jsonObject)
      }
    }
}
```

Usage:
@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
case class MyTable(
  @Id id: Long,
  content: JsonB[MyContent]
) derives DbCodec

**Comment by AugustNagro** [comment]
Yes looks excellent, thanks for sharing.

I think with a few changes we can make it fully generic, and maybe remove the need for the Json[T] and JsonB[T] marker types. Let me take a stab and I'll share a wip MR.

**Comment by AugustNagro** [comment]
Hey @jivanic-demystdata please review when you get a chance:

https://github.com/AugustNagro/magnum/pull/49

I updated the readme with an example using Play Json:

```scala
trait PlayJsonDbCodec[A] extends JsonDbCodec[A]
object PlayJsonDbCodec:
  def derived[A](using jsonCodec: OFormat[A]): PlayJsonDbCodec[A] = new:
    def encode(a: A): String = jsonCodec.writes(a).toString
    def decode(json: String): A = jsonCodec.reads(Json.parse(json)).get

case class LastService(mechanic: String, date: LocalDate) derives PlayJsonDbCodec
object LastService:
  given OFormat[LastService] = Json.format[LastService]

@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
case class Car(
    @Id id: Long,
    lastService: LastService
) derives DbCodec
```

Lmk what you think of the approach. I still need to add some tests / resolve todos.

Also, I'm curious why your codec uses the queryExprs of `?::json` and `?::jsonb` since it seemed to work fine in the simple insert/read tests with just `?`.

**Comment by guizmaii** [comment]
> Also, I'm curious why your codec uses the queryExprs of ?::json and ?::jsonb since it seemed to work fine in the simple insert/read tests with just ?.

I have no idea myself. I tried to follow what I've read on internet, I guess. If it works without that's great :)
