### ISSUE TITLE
Nullable UUID encoding problem given None

### ISSUE THREAD

**Issue by mbablok** [AugustNagro/magnum#30]
Hello,

thank you for a very nice library.

I stumpled upon a problem with a nullable UUID column in a postgres DB. When a case class instance field has `None` I get  a runtime exception ```org.postgresql.util.PSQLException: Unknown Types value.```

I created a test case to demonstrate it.

https://github.com/mbablok/magnum/commit/2d387a89b23ea1fe556481609242346210eecccc

**Comment by AugustNagro** [comment]
Thanks for the report, please review this MR and I can make a new release.

**Comment by AugustNagro** [comment]
Actually, MR needs a little more thought. Will let you know when ready for review.

**Comment by mbablok** [comment]
Sure, thank you.

**Comment by AugustNagro** [comment]
Hey, thanks for the patience. I think this is ready now, can you review?

https://github.com/AugustNagro/magnum/pull/31

**Comment by mbablok** [comment]
No problem.

I work only with PG only so I tend to forget about other DBs. Thanks a lot.

BTW - I found out this is quite easy to have JSONB support in PG - one codec and some readme would suffice. Would you like me to submit a PR for that or help in another way?

**Comment by AugustNagro** [comment]
Released: https://github.com/AugustNagro/magnum/releases/tag/v1.2.1

> BTW - I found out this is quite easy to have JSONB support in PG - one codec and some readme would suffice. Would you like me to submit a PR for that or help in another way?

Sure, that would be welcome!
