### ISSUE TITLE
Frag equivalent of sql interpolator?

### ISSUE THREAD

**Issue by fdietze** [AugustNagro/magnum#35]
Hi, what is the equivalent `Frag` of writing `sql"... $param"`? 
I thought it would be `Frag("... ? ", IArray(param))`, but that doesn't return any result rows, because the param is probably not passed correctly to the db.

I'm using sqlite.

```scala
def getReplyIds(parent_id: Long)(using con: DbCon): Vector[Long] = {


  // this works
  val frag = sql"select id from post where parent_id = ${parent_id}"

  // this doesn't work:
  // val frag = Frag("select id from post where parent_id = ?", params = IArray(parent_id))

  frag.query[Long].run()
}
```

For context, I'm experimenting with [sqlc](https://sqlc.dev/) to generate Scala functions from raw sql queries: https://github.com/fdietze/sqlc-gen-from-template

**Comment by AugustNagro** [comment]
Hi, Frag takes three arguments: https://github.com/AugustNagro/magnum/blob/master/magnum/src/main/scala/com/augustnagro/magnum/Frag.scala

You're missing the third `writer: FragWriter` argument (you do not want the default Frag.emptyWriter)

For an example on how to implement FragWriter, see for example https://github.com/AugustNagro/magnum/blob/master/magnum/src/main/scala/com/augustnagro/magnum/Spec.scala#L38

**Comment by fdietze** [comment]
For reference, this is what I came up with:

```Scala
def fragWriter(params: Seq[Any]): FragWriter = { (preparedStatement, startPos) =>
  var i = 0
  val n = params.size
  while (i < n) {
    val param = params(i)
    param match {
      case param: Int    => preparedStatement.setInt(startPos + i, param)
      case param: Long   => preparedStatement.setLong(startPos + i, param)
      case param: String => preparedStatement.setString(startPos + i, param)
      case param: Double => preparedStatement.setDouble(startPos + i, param)
    }
    i += 1
  }
  startPos + params.size
}
```
