### ISSUE TITLE
Support for Arrays of Enums (Postgres)

### ISSUE THREAD

**Issue by Nexus6** [AugustNagro/magnum#36]
Version: magnum/magnumpg 1.2.1

Let's say I have a Scala enum of 
```
enum Color derives DbCodec:
  case Red, Green, Blue
```

I've been experimenting with Magnum+PG, and it seems like Table column types of Color work fine - serialization to strings in the db is not a problem.  Where I have db tables with column types like text[], using Scala types like List[String] to represent them also seems to work fine (I've only tested queries so far, not inserts/updates) with Magnum. But trying to specify column types like List[Color], as in

```
@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
final case class Rainbow(
  @Id id:Int,
  colors:List[Color]
) derives DbCodec
```

...gets me a compile error: "Cannot find a DbCodec instance for scala.collection.immutable.List[Color] ".

Since enum support is partially there (at least for things that can be serialized to strings), and Array support is there, it would make sense to me that they work together.

Is this something that just isn't implemented yet, or something that won't be available with Magnum out of the box?  Are there any work-arounds that come to mind?

Even better than having the above working, would be having it work with PG's native enum types and Array types, eg. color[] columns where 'color' is a user-defined PG enum type.

**Comment by AugustNagro** [comment]
> Is this something that just isn't implemented yet, or something that won't be available with Magnum out of the box

Thanks for filing; support just isn't implemented yet. Please review & try https://github.com/AugustNagro/magnum/pull/37 when you get a chance.

> Even better than having the above working, would be having it work with PG's native enum types and Array types, eg. color[] columns where 'color' is a user-defined PG enum type.

In the linked MR, you will see there's tests for both 

Array of Pg Enum <-> Seq of Scala Enum
Array of Pg Varchar <-> Seq of Scala Enum

They require different DbCodec givens, since the JDBC array types are different for each case.

**Comment by Nexus6** [comment]
Fantastic, thanks for the quick feature-add, I'll test #37 in the next few days. If it works I'll be able to remove some hacky work-around code from my project!

Related: will this new feature also support the "Array of Pg **text**" <-> Seq of Scala Enum" case?
I suspect the answer is 'yes' and if so it might be nice to have that in the docs somewhere simply because it's probably common for devs to use 'text' types instead of 'varchar' types when they need to store strings in PG, including in arrays.

**Comment by AugustNagro** [comment]
> will this new feature also support the "Array of Pg text" <-> Seq of Scala Enum" case

Yes; it will definitely support this; JDBC considers both text and varchar to be JDBCType.VARCHAR. I added to the readme:

```
If instead your Postgres type is an array of varchar or text, use the following import: 
```

**Comment by AugustNagro** [comment]
Thanks for trying it out and this is great feedback. I'll be able to take
action & respond in detail next week when things are less busy.

**Comment by Nexus6** [comment]
Re: my previous comment...

I've opened a new issue #41 for the .sbt/.credentials warnings. The docker+testcontainers test dependency was a bigger PITA but I think I've got a working setup now, the evidence being that "sbt test" now completes successfully on my dev machine.
[info] Passed: Total 6, Failed 0, Errors 0, Passed 6
[info] Passed: Total 203, Failed 0, Errors 0, Passed 203

This area - (Magnum) developer docs - could use a lot of improvement, there's just one sentence devoted to it now unless I've missed something. I should probably open a separate Issue on this.

**Comment by Nexus6** [comment]
Regarding my problem with getting @SqlName to work with enums: the problem seems to go away - @SqlName annotations on enums are respected, when I do not also annotate the enum with `@Table`.

The following works - it both compiles and passes the project's PgCodecTests, when all Color->ColorModel references are changed of course::
```
import com.augustnagro.magnum.{DbCodec, SqlName}

@SqlName("Color")
enum ColorModel derives DbCodec:
  case Red, Green, Blue
```

The following:,
```
import com.augustnagro.magnum.*

@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
@SqlName("Color")
enum ColorModel derives DbCodec:
  case Red, Green, Blue
```
fails tests with errors like:
```
PgCodecTests:
==> X PgCodecTests.select all MagUser  0.413s com.augustnagro.magnum.SqlException: Error executing query:
SELECT id, name, friends, matrix, test, dates, bx, c, iv, l, lSeg, p, pnt, poly, colors, colorMap FROM mag_user
With message:
Red not convertible to ColorModel
```

You might ask why I was inclined to add the `@Table` annotation to the Scala enum definition in the first place. The answer is that 
the example in the documentation, in the "Scala 3 Enum & NewType Support" section, shows exactly this, so I thought `@Table` was some kind of required magic to make PG enum support work. Instead, it's not necessary at all, and actually breaks `@SqlName` functionality on enums.

**Comment by AugustNagro** [comment]
```scala

import com.augustnagro.magnum.*

@Table(PostgresDbType, SqlNameMapper.CamelToSnakeCase)
@SqlName("Color")
enum ColorModel derives DbCodec:
  case Red, Green, Blue
```

This fails because [postgres enums are case sensitive](https://www.postgresql.org/docs/current/datatype-enum.html#DATATYPE-ENUM-IMPLEMENTATION-DETAILS). 

SqlNameMapper.CamelToSnakeCase maps Red -> red, Green -> green, and Blue -> blue.  If you change to SqlNameMapper.SameCase, you'll see that the test passes.

There was an error in the PR where SqlName annotations were not being respected for individual case labels that I've fixed now.

**Comment by AugustNagro** [comment]
For point (4):

> Just to cause trouble, I decided to create a table with two enum columns, one backed by a text[] column in the db, and one backed by an enum[] column

That's a good catch. The long term solution is to support an annotation like `@SqlArrayCodecOverride[A](codec: SqlArrayCodec[A])`. You could then annotate the case fields to explicitly set which codec to use.

Unfortunately it's not a simple of change to make, and we probably also want to have an equivalent `@DbCodecOverride` for DbCodec. Hopefully it's a rare use-case, and there are workarounds. I'll file a new issue to track it.

**Comment by AugustNagro** [comment]
Merged https://github.com/AugustNagro/magnum/pull/37 so I'll close this issue. Thanks again for the involvement here.
