### ISSUE TITLE
Using Partials

### ISSUE THREAD

**Issue by EvgenyAfanasev** [AugustNagro/magnum#54]
Can I split my sql fragments on multiple partials ? 

for example:

```scala
val partial = sql"code = $code AND color = $color"
val fragment = sql"SELECT * from example WHERE $partial"
```

**Comment by EvgenyAfanasev** [comment]
Sorry for duplicate https://github.com/AugustNagro/magnum/issues/34

**Comment by AugustNagro** [comment]
No problem! We should hopefully land this feature in the next release.
