### ISSUE TITLE
Bug with multiple where section in spec

### ISSUE THREAD

**Issue by EvgenyAfanasev** [AugustNagro/magnum#58]
Hi. When I run multiple `.where` method on spec instance I get error "index out of column count". You can try it with new test:

```scala
test("findAll spec with multiple conditions"):
    connect(ds()):
      val topSpeed = 211
      val model = "Ferrari F8 Tributo"
      val spec = Spec[Car]
        .where(sql"${car.topSpeed} > $topSpeed")
        .where(sql"${car.model} = $model")
      assertEquals(carRepo.findAll(spec), Vector(allCars(1)))
```

I already fix it, wait please PR

**Comment by AugustNagro** [comment]
Merged. I'm sorry there was such poor coverage for Spec.build. I'll work to improve this before the next release.

Closing the issue now but feel free to comment or re-open.
